In [8]:
import numpy as np
import time

# zip

In [5]:
l1=[1,2,3,4]
l2=[4,5,6,7]
list(zip(l1,l2))

[(1, 4), (2, 5), (3, 6), (4, 7)]

In [26]:
# By using list
a = 10000000
list1 =list(range(a))
list2 =list(range(a))
strt = time.time()
add = list1+list2
end = time.time()
print(end-strt)

0.24407482147216797


In [28]:
# By using numpy array
a = 100000
list1 = np.array(list(range(a)))
list2 = np.array(list(range(a)))
strt = time.time()
add = list1+list2
end = time.time()
print(end-strt)


0.6498496532440186


In [ ]:
- we use numpy arrays becaus it is very faster than lists.

# create numpy arrays

In [35]:
hello=np.array([1,2,3,4,'Harry']) # this will not work
hello

array(['1', '2', '3', '4', 'Harry'], dtype='<U11')

In [37]:
type(hello)

numpy.ndarray

In [54]:
nikesh=np.array([1,2,3,4,5])
nikesh.shape

(5,)

In [35]:
np.array([[1,2,3],[2,3,4]])  # For 2 list we have to give two dimensions

array([[1, 2, 3],
       [2, 3, 4]])

In [47]:
np.array([[1,2,3],[2,3,4]])

array([[1, 2, 3],
       [2, 3, 4]])

In [95]:
a = 100000
list1 = list(range(a))
start = time.time()
square = [x**2 for x in list1]
end = time.time()
print(square[0:11])
print(end-start)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
0.0154571533203125


In [93]:
arr1 = np.array(list(range(a)))
strt = time.time()
sqre= arr1**2
end = time.time()
print(sqre[0:11])
print(end-strt)

[  0   1   4   9  16  25  36  49  64  81 100]
0.0


- Here we can see numpy is very fast.

# creating numpy arrays

In [2]:
import numpy as np

In [12]:
arr1 = np.array([1,2,3,4])  # 1 d array
arr1

array([1, 2, 3, 4])

In [14]:
arr2 = np.array([[1,2,3,4],[1,4,5,6]]) # 2d array
arr2

array([[1, 2, 3, 4],
       [1, 4, 5, 6]])

In [6]:
# creating arrays from zeroes
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
# creating arrays from ones
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.full((2,2),6)  # 2*2 matrix filled with 6

array([[6, 6],
       [6, 6]])

In [29]:
np.eye(5)  # 5*5 Identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
np.arange(1,100,9) # 1 dekhi 100 samma 9 add hudai janxa (100 exclusive )

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [41]:
np.linspace(1,100,5) # 5 elements ko equally spaced array dinxa

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [52]:
my_arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])
my_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [54]:
my_arr.shape

(4, 3)

In [58]:
my_arr.size # total no of elements

12

In [62]:
my_arr.ndim # dimension

2

In [64]:
my_arr.dtype

dtype('int32')

In [68]:
# changig data types

my_arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]], dtype="float32")

In [70]:
my_arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]], dtype=float32)

In [74]:
n=my_arr.astype('float64')

In [76]:
n.dtype

dtype('float64')

In [78]:
reshaped = my_arr.reshape((3,4))

In [80]:
reshaped

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 11., 12., 13.]], dtype=float32)

In [82]:
arr=reshaped.reshape((6,2))
arr

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 11.],
       [12., 13.]], dtype=float32)

In [86]:
my_arr.flatten()  # convert  2D to 1D

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 11., 12., 13.],
      dtype=float32)

# Indexing and slicing

In [91]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [93]:
flat=arr.flatten()

In [95]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [97]:
flat[0]

1

In [99]:
flat[3]

4

In [101]:
flat[4]

5

In [103]:
flat[3:6]

array([4, 5, 6])

In [107]:
flat[:5] # same as flat[0:5]

array([1, 2, 3, 4, 5])

In [111]:
flat[3:] #same as flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [115]:
flat[::2] # evry second element

array([ 1,  3,  5,  7,  9, 11])

Slicing returns a view, not a copy! Changes affect the original array.**
This might seem counterintuitive since Python lists create copies when sliced. But in NumPy, slicing returns a view of the original array. Both the sliced array and the original array share the same data in memory, so changes in the slice affect the original array.

In [117]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [121]:
b = flat[3:7]
b

array([4, 5, 6, 7])

In [123]:
b[0]=4444

In [125]:
b

array([4444,    5,    6,    7])

In [127]:
flat

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   10,   11,
         12])

if we want to use copy then

In [131]:
b = flat.copy()

In [133]:
b

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   10,   11,
         12])

In [135]:
b[2] = 100

In [137]:
b

array([   1,    2,  100, 4444,    5,    6,    7,    8,    9,   10,   11,
         12])

In [139]:
flat

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   10,   11,
         12])

- Hence there is no change 

# Fancy indexing and boolean masking

In [143]:
arr = np.array([1,2,3,4,5,6,7,8])
arr[[0,4,6]] # 0,4,6 are index and it gives values of that particular indexes

array([1, 5, 7])

# Boolean masking

In [152]:
arr = np.array([1,2,3,4,5,6,7,8])
arr[arr>3]   # condition : values greater than 3

array([4, 5, 6, 7, 8])

# Excerise

- Create a 3×3 array filled with random numbers and print its shape.

In [156]:
arr = np.array([[1,2,3],[4,5,6],[8,9,55]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 55]])

In [160]:
arr.shape

(3, 3)

- Convert an array of floats [1.1, 2.2, 3.3] into integers.

In [163]:
arr2 = np.array([1.1, 2.2, 3.3])
arr2

array([1.1, 2.2, 3.3])

In [165]:
arr2.dtype

dtype('float64')

In [185]:
arr2 = np.array([1.1, 2.2, 3.3])
arr2

array([1.1, 2.2, 3.3])

In [183]:
arr2 = np.array([1.1,2.2,3.3], dtype="int")
arr2

array([1, 2, 3])

In [187]:
arr3=arr2.astype('int')

In [189]:
arr3

array([1, 2, 3])

- Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6]

In [198]:
arr4 = np.array([1,2,3,4,5,6])
arr4[[1,3,5]]

array([2, 4, 6])

- Reshape a 1D array of size 9 into a 3×3 matrix.

In [201]:
arr5 = np.array([2,4,5,6,7,8,9,8,6])
arr5.reshape((3,3))

array([[2, 4, 5],
       [6, 7, 8],
       [9, 8, 6]])

- Use boolean masking to filter numbers greater than 50 in an array.

In [204]:
arr6=np.array([1,2,3,55,67,87,4,5,6,89])
arr6[arr6>50]

array([55, 67, 87, 89])

# Data types in numpy

In [209]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [211]:
arr.astype('float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [215]:
arr.nbytes  # 20 bytes used

20

# Broadcasting

- vectorization: Fixing the loop problems

In [232]:
arr = np.array([1,2,3,4,5])
result = arr**2 # vectorized operation
print(result)  # This is faster than using loops

[ 1  4  9 16 25]


In [234]:
result + 20

array([21, 24, 29, 36, 45])

In [240]:
arr1 = np.array([[1,2,3],[6,7,8]])
arr2 = np.array([1,2,4])
result = arr1+ arr2  # Broadcasting arr2 accross arr1
print(result)

[[ 2  4  7]
 [ 7  9 12]]


# Hand on applying broadcasting

In [247]:
data = np.array([[10,20,30],
                 [50,60,70],
                 [80,90,100]])
# Finding mean and std of data
mean=data.mean(axis=0)
std=data.std(axis=0)
# Normalizing the data using broadcasting
normalized_data = (data-mean)/std
print(normalized_data)

[[-1.27872403 -1.27872403 -1.27872403]
 [ 0.11624764  0.11624764  0.11624764]
 [ 1.16247639  1.16247639  1.16247639]]


# Built in mathematical functions in numpy

In [250]:
arr = np.array([1,2,3,4,5])
np.mean(arr)

3.0

In [252]:
np.max(arr)

5

In [256]:
np.min(arr)

1

In [260]:
np.var(arr) # variance

2.0

In [262]:
np.std(arr)

1.4142135623730951

In [264]:
np.sum(arr)

15

In [266]:
np.prod(arr)

120

In [270]:
np.median(arr)

3.0

In [272]:
np.percentile(arr,50)

3.0

In [276]:
np.argmax(arr) # In index 4 there is maxium value

4

In [280]:
np.argmin(arr) # In index 0 there is min value

0

In [282]:
np.corrcoef(arr)

1.0

In [286]:
arr2=np.array([1,1,2,3,4,55,55,6,7,7,8,8,9,5])
np.unique(arr2) # Give unique value

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 55])

In [288]:
np.cumsum(arr)

array([ 1,  3,  6, 10, 15])